#!/bin/bash

# Interactive
#docker run -t -i \
#       -e GREENMAIL_OPTS='-Dgreenmail.setup.test.smtp -Dgreenmail.setup.test.imap -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.users=delta1:delta1,delta2:delta2 -Dgreenmail.verbose' \
#       -p 3025:3025 -p 3110:3110 -p 3143:3143 -p 3465:3465 -p 3993:3993 -p 3995:3995  greenmail/standalone:1.5.8

# Daemon
docker run -d --name greenmail \
       -e GREENMAIL_OPTS='-Dgreenmail.setup.test.smtp -Dgreenmail.setup.test.imap -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.users=delta1:delta1,delta2:delta2 -Dgreenmail.verbose' \
       -p 3025:3025 -p 3110:3110 -p 3143:3143 -p 3465:3465 -p 3993:3993 -p 3995:3995  greenmail/standalone:1.5.8
