name: 'Windows'
on: push


jobs:
  build-and-test:
    name: "Build & Test"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: System info
        run: |
          rustc -vV
          rustup -vV
          cargo -vV
          npm --version
          node --version
      
      - name: Pull submodule
        run: npm run submodule

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ${{ env.APPDATA }}/npm-cache # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
     
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: deltachat-core-rust/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies & build
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --verbose
 
      - name: Test
        run: npm run test
